# Generated by Django 3.2.7 on 2021-11-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='img',
            field=models.TextField(default='DEFAULT VALUE'),
        ),
    ]
